In [4]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker

In [91]:
input_path  = "UK-Sanctions-List.csv"

df = pd.read_csv(input_path,header=1)  #header is at index 1
df.head(5)

/var/folders/mm/n6ct31451898z276zsj_w5lm0000gn/T/ipykernel_30071/3459786965.py:3: DtypeWarning: Columns (48,49,50,51,52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(input_path,header=1)  #header is at index 1

,Last Updated,Unique ID,OFSI Group ID,UN Reference Number,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,...,IMO number,Current owner/operator (s),Previous owner/operator (s),Current believed flag of ship,Previous flags,Type of ship,Tonnage of ship,Length of ship,Year Built,Hull identification number (HIN)
0,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
print(df.shape)
print(f'Unique entities (Unique ID): {df["Unique ID"].nunique()}')

(57033, 58)
Unique entities (Unique ID): 6046

In [13]:
for i, col in enumerate(df.columns, 1):
    print(f'{i}. {col}')

1. Last Updated
2. Unique ID
3. OFSI Group ID
4. UN Reference Number
5. Name 6
6. Name 1
7. Name 2
8. Name 3
9. Name 4
10. Name 5
11. Name type
12. Alias strength
13. Title
14. Name non-latin script
15. Non-latin script type
16. Non-latin script language
17. Regime Name
18. Designation Type
19. Designation source
20. Sanctions Imposed
21. Other Information
22. UK Statement of Reasons
23. Address Line 1
24. Address Line 2
25. Address Line 3
26. Address Line 4
27. Address Line 5
28. Address Line 6
29. Address Postal Code
30. Address Country
31. Phone number
32. Website
33. Email address
34. Date Designated
35. D.O.B
36. Nationality(/ies)
37. National Identifier number
38. National Identifier additional information
39. Passport number
40. Passport additional information
41. Position
42. Gender
43. Town of birth
44. Country of birth
45. Type of entity
46. Subsidiaries
47. Parent company
48. Business registration number (s)
49. IMO number
50. Current owner/operator (s)
51. Previous owner/operator (s)
52. Current believed flag of ship
53. Previous flags
54. Type of ship
55. Tonnage of ship
56. Length of ship
57. Year Built
58. Hull identification number (HIN)

### Name fields explained

The dataset uses **7 name fields**, which can be confusing:

| Field | Purpose |
|-------|---------|
| `Name 6` | The last name/surname of the individual OR the full name of the entity or ship|
| `Name 1` | First name (populated for individuals; blank for many entities) |
| `Name 2` | The second name (NOT surname) of the individual|
| `Name 3–5` | Additional parts |
| `Name type` | Whether this row's name is a `Primary Name`, `Alias`, or `Primary Name Variation` |
| `Name non-latin script` |  The non-Latin script version of a name |
| `Non-latin script type` | The type of non-Latin script for the name |
| `Non-latin script language` | The language of the non-Latin script name |
| `Alias strength` | `Good quality` vs `Low quality(empty and blank included)` |

In [26]:
for col in ['Name 6','Name 1','Name 2','Name 3','Name 4','Name 5']:
    pct_filled = df[col].notna().mean() * 100
    print(f'{col}: {pct_filled:.1f}% populated')

print(df['Name type'].value_counts())

print(df.drop_duplicates('Unique ID')['Designation Type'].value_counts())

Name 6: 99.8% populated
Name 1: 41.9% populated
Name 2: 21.2% populated
Name 3: 4.5% populated
Name 4: 0.8% populated
Name 5: 0.2% populated
Name type
Alias                     34303
Primary name               7244
Primary Name Variation     6153
Primary Name               6034
Primary name variation     3233
ALias                         2
Name: count, dtype: int64
Designation Type
Individual    3883
Entity        1531
Ship           632
Name: count, dtype: int64

This are the sanction type which are banned from any banking activity.

Asset freeze (This is the most common and absolute ban on all banking/financial services for the target).

Prohibition on correspondent banking

Prohibition on correspondent banking and clearing

Prohibition on Correspondent banking relationships and processing payments

Prohibition on sterling clearing

### Final Field

The dataset has 58 columns from which we have decided to keep only this fields:

| Field |
|-------|
| `Unique ID` |
| `Name 1-6` |
| `Regime Name` |
| `Designation Type` | 
| `Sanctions Imposed` | 
| `Address Postal Code` | 
| `Address Country` | 
| `Nationality(/ies)` | 
| `Country of birth` |
| `Phone Number` | 
| `DOB` | 
| `Gender` |
| `National Identifier number` |
| `Passport number` |
| `IMO number` | Not Imp but just incase

### Missing Value

In [145]:
df['Passport number'].isna().value_counts()

for col in ['Name 6','Name 1','Name 2','Name 3','Name 4','Name 5','Passport number',
            'Name non-latin script','Regime Name','Designation Type','Sanctions Imposed',
            'Address Country','Phone number','Email address','D.O.B','Nationality(/ies)',
            'Country of birth','National Identifier number','Passport number','IMO number']:
    pct_filled = df[col].notna().mean() * 100
    print(f'{col}: {pct_filled:.1f}% populated')

Name 6: 99.8% populated
Name 1: 41.9% populated
Name 2: 21.2% populated
Name 3: 4.5% populated
Name 4: 0.8% populated
Name 5: 0.2% populated
Passport number: 18.6% populated
Name non-latin script: 13.5% populated
Regime Name: 100.0% populated
Designation Type: 100.0% populated
Sanctions Imposed: 100.0% populated
Address Country: 78.8% populated
Phone number: 43.8% populated
Email address: 42.2% populated
D.O.B: 43.5% populated
Nationality(/ies): 38.2% populated
Country of birth: 38.5% populated
National Identifier number: 12.2% populated
Passport number: 18.6% populated
IMO number: 1.5% populated

#### The DOB has diffrent format

In [82]:
import re
def classify_dob(s):
    s = str(s).strip()
    if re.match(r'^\d{2}/\d{2}/\d{4}$', s):        return 'Full date (dd/mm/yyyy)'
    if re.match(r'^dd/mm/\d{4}$', s):               return 'Year only (dd/mm placeholder)'
    if re.match(r'^dd/\d{2}/\d{4}$', s):               return 'Month and Year  (mm/yyyy placeholder)'
    if re.match(r'^\d{4}$', s):                     return 'Year only (bare yyyy)'
    if re.search(r'(?i)between|circa|approx', s):   return 'Approximate (text)'
    return 'Other / partial'

dob_series = df['D.O.B'].dropna()
dob_classes = dob_series.apply(classify_dob).value_counts()
print(dob_classes)

print('Sample DOB values by category:')
for cat in dob_classes.index:
    examples = dob_series[dob_series.apply(classify_dob) == cat].unique()[:3]
    print(f'  {cat}: {list(examples)}')

D.O.B
Full date (dd/mm/yyyy)                   16585
Year only (dd/mm placeholder)             7510
Month and Year  (mm/yyyy placeholder)      526
Year only (bare yyyy)                      186
Other / partial                              2
Name: count, dtype: int64
Sample DOB values by category:
  Full date (dd/mm/yyyy): ['30/01/1972', '12/11/1967', '24/10/1971']
  Year only (dd/mm placeholder): ['dd/mm/1958', 'dd/mm/1950', 'dd/mm/1955']
  Month and Year  (mm/yyyy placeholder): ['dd/09/1958', 'dd/08/1977', 'dd/09/1977']
  Year only (bare yyyy): ['1971', '1955', '1956']
  Other / partial: ["'00/00/1975", '15/08/19yy']

### Name type casing inconsistency

In [39]:
print(df['Name type'].value_counts())

Name type
Alias                     34303
Primary name               7244
Primary Name Variation     6153
Primary Name               6034
Primary name variation     3233
ALias                         2
Name: count, dtype: int64

### A ' in front of the phone number

In [50]:
phones = df['Phone number'].dropna()
bad = phones[phones.str.startswith("'")]
print(f'Phone numbers with \' {len(bad)}')
print(f'Sample values: {bad.unique().tolist()[:5]}')

Phone numbers with ' 1011
Sample values: ["'0202-104748", "'0300-8209199", "'042-6812081", "'0271-2167285", "'00375(17)7762032"]

In [51]:
exact_dups = df.duplicated().sum()
uid_only_dups = df.duplicated(subset=['Unique ID']).sum()

print(f'Exact duplicate rows         : {exact_dups}')
print(f'Rows with a repeated Unique ID: {uid_only_dups:,} (expected — this is the cross-product design)')

Exact duplicate rows         : 650
Rows with a repeated Unique ID: 50,987 (expected — this is the cross-product design)

# Data Transformation

In [ ]:
def build_full_name(row: pd.Series) -> str:
    """
    Combines Name 1 through Name 6

    Name structure (from OFSI documentation):
      Name 1 = First name (populated for individuals; blank for many entities)
      Name 2 = The second name (NOT surname) of the individual
      Name 3–5 = Additional parts
      Name 6 = Last Name/ Surname
    """
    name_cols = ['Name 1', 'Name 2', 'Name 3', 'Name 4', 'Name 5', 'Name 6']
    # Filter out nulls and join with a space
    names = [str(row[col]).strip() for col in name_cols if pd.notnull(row[col]) and str(row[col]).strip() != '']
    return ' '.join(names)

In [61]:
temp = df.drop_duplicates(subset=["Name 1"]).head(5)
temp['combined_name'] = temp.apply(build_full_name,axis=1)
temp

,Last Updated,Unique ID,OFSI Group ID,UN Reference Number,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,...,Current owner/operator (s),Previous owner/operator (s),Current believed flag of ship,Previous flags,Type of ship,Tonnage of ship,Length of ship,Year Built,Hull identification number (HIN),combined_name
0,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE
1061,14/04/2026,AFG0006,7172.0,TAi.002,AKHUND,MOHAMMAD,HASSAN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MOHAMMAD HASSAN AKHUND
1101,29/04/2026,AFG0007,6909.0,TAi.003,MOHAMMAD JAN,Abdul Kabir,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Abdul Kabir MOHAMMAD JAN
1107,29/04/2026,AFG0007,6909.0,TAi.003,ABDUL,KABIR,MUHAMMAD JAN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,KABIR MUHAMMAD JAN ABDUL
1113,29/04/2026,AFG0007,6909.0,TAi.003,JAN,ABDUL,KABIR,MUHAMMAD,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ABDUL KABIR MUHAMMAD JAN

In [65]:
def combine_countries(row):
    """Combines all geographic references"""
    cols = ['Address Country', 'Nationality(/ies)', 'Country of birth']
    countries = [str(row[col]).strip() for col in cols if pd.notnull(row[col]) and str(row[col]).strip() != '']
    return countries
def clean_list(item_list):
    """Helper function to remove nulls, deduplicate, and join lists into a string"""
    clean_items = [str(i).strip() for i in item_list if pd.notnull(i) and str(i).strip() != '']
    return ', '.join(sorted(list(set(clean_items))))

In [66]:
temp = df.drop_duplicates(subset=["Name 1"]).head(5)
temp['combined_name'] = temp.apply(combine_countries,axis=1)
temp['combined_name'] = temp['combined_name'].apply(clean_list)
temp

,Last Updated,Unique ID,OFSI Group ID,UN Reference Number,Name 6,Name 1,Name 2,Name 3,Name 4,Name 5,...,Current owner/operator (s),Previous owner/operator (s),Current believed flag of ship,Previous flags,Type of ship,Tonnage of ship,Length of ship,Year Built,Hull identification number (HIN),combined_name
0,16/04/2026,AFG0001,12703.0,TAe.010,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Iran
1061,14/04/2026,AFG0006,7172.0,TAi.002,AKHUND,MOHAMMAD,HASSAN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan
1101,29/04/2026,AFG0007,6909.0,TAi.003,MOHAMMAD JAN,Abdul Kabir,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan
1107,29/04/2026,AFG0007,6909.0,TAi.003,ABDUL,KABIR,MUHAMMAD JAN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan
1113,29/04/2026,AFG0007,6909.0,TAi.003,JAN,ABDUL,KABIR,MUHAMMAD,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Afghanistan

In [67]:
"""Alias                     34303
Primary name               7244
Primary Name Variation     6153
Primary Name               6034
Primary name variation     3233
ALias                         2
"""


def normalise_name_type(name_type: str) -> str:
    """Standardise case variations in Name type field."""
    if pd.isna(name_type):
        return "Unknown"
    nt = str(name_type).strip()
    mapping = {
        "Primary Name"          : "Primary Name",
        "Primary name"          : "Primary Name",        # inconsistent casing fix
        "Primary Name Variation": "Primary Name Variation",  
        "Primary name variation": "Primary Name Variation",  # inconsistent casing fix
        "Alias"                 : "Alias",
        "ALias"                 : "Alias",               # typo fix
    }
    return mapping.get(nt, nt)

In [ ]:
print(df['Name type'].value_counts())
temp = df.drop_duplicates(subset=["Name type"]).head(7)
print(temp['Name type'].value_counts())
temp['Name type'] = temp["Name type"].apply(normalise_name_type)
print(temp['Name type'].value_counts())

Name type
Alias                     34303
Primary name               7244
Primary Name Variation     6153
Primary Name               6034
Primary name variation     3233
ALias                         2
Name: count, dtype: int64
Name type
Primary Name              1
Alias                     1
Primary Name Variation    1
Primary name              1
ALias                     1
Primary name variation    1
Name: count, dtype: int64
Name type
Primary Name              2
Alias                     2
Primary Name Variation    2
Unknown                   1
Name: count, dtype: int64

In [92]:
def clean_dob_for_kyc(dob_str):
    """
    Cleans messy DOB formats from the UK Sanctions list.
    Retains maximum precision without inventing false dates.
    """
    if pd.isna(dob_str):
        return None
        
    s = str(dob_str).strip()
    
    # Full date (e.g., "30/01/1972") -> Keep as is
    if re.match(r'^\d{2}/\d{2}/\d{4}$', s):
        return s
        
    # Year only with placeholders (e.g., "dd/mm/1958") -> Extract "1958"
    match_year_ph = re.match(r'^dd/mm/(\d{4})$', s, re.IGNORECASE)
    if match_year_ph:
        return match_year_ph.group(1)
        
    # Month & Year with placeholders (e.g., "dd/09/1958") -> Extract "09/1958"
    match_mo_year = re.match(r'^dd/(\d{2})/(\d{4})$', s, re.IGNORECASE)
    if match_mo_year:
        return f"{match_mo_year.group(1)}/{match_mo_year.group(2)}"
        
    # Bare year (e.g., "1971") -> Keep as is
    if re.match(r'^\d{4}$', s):
        return s
        
    # Handle "Other" edge cases found in your analysis
    s = s.replace("'", "") # Remove rogue single quotes like "'00/00/1975"
    
    # Example: "00/00/1975" -> Extract "1975"
    match_zeros = re.search(r'00/00/(\d{4})', s)
    if match_zeros:
        return match_zeros.group(1)
        
    # Example: "15/08/19yy" -> Standardize unknown years with "XX"
    s = s.replace("yy", "XX").replace("YY", "XX")
    
    return s

In [94]:
temp = df.copy()
temp['D.O.B'] = temp['D.O.B'].apply(clean_dob_for_kyc)

def classify_dob(s):
    s = str(s).strip()
    if re.match(r'^\d{2}/\d{2}/\d{4}$', s):        return 'Full date (dd/mm/yyyy)'
    if re.match(r'^dd/mm/\d{4}$', s):               return 'Year only (dd/mm placeholder)'
    if re.match(r'^\d{2}/\d{4}$', s):               return 'Month and Year  (mm/yyyy placeholder)'
    if re.match(r'^\d{4}$', s):                     return 'Year only (bare yyyy)'
    if re.search(r'(?i)between|circa|approx', s):   return 'Approximate (text)'
    return 'Other / partial'

dob_series = temp['D.O.B'].dropna()
dob_classes = dob_series.apply(classify_dob).value_counts()
print(dob_classes)

print('Sample DOB values by category:')
for cat in dob_classes.index:
    examples = dob_series[dob_series.apply(classify_dob) == cat].unique()[:3]
    print(f'  {cat}: {list(examples)}')

D.O.B
Full date (dd/mm/yyyy)                   16585
Year only (bare yyyy)                     7697
Month and Year  (mm/yyyy placeholder)      526
Other / partial                              1
Name: count, dtype: int64
Sample DOB values by category:
  Full date (dd/mm/yyyy): ['30/01/1972', '12/11/1967', '24/10/1971']
  Year only (bare yyyy): ['1958', '1950', '1955']
  Month and Year  (mm/yyyy placeholder): ['09/1958', '08/1977', '09/1977']
  Other / partial: ['15/08/19XX']

In [136]:
def aggregate_entity(group):
    # Entity Type
    entity_types = group['Designation Type'].dropna().unique()
    entity_type = entity_types[0] if len(entity_types) > 0 else "Unknown"
    
    # Names (Separating Primary from Aliases)
    primary_names = group[group['Clean_Name_Type'] == 'Primary Name']['Full_Name'].tolist()
    primary_name = primary_names[0] if primary_names else group['Full_Name'].iloc[0]
    
    all_names = group['Full_Name'].unique().tolist()
    aliases = [n for n in all_names if n != primary_name]
    
    # Aggregating multi-value fields into lists
    dobs = group['Clean_DOB'].tolist()
    countries = []
    for c_list in group['All_Countries_List']:
        countries.extend(c_list)
        
    passports = group['Passport number'].tolist()
    nat_ids = group['National Identifier number'].tolist()
    
    # Extra KYC Fields
    sanctions = group['Sanctions Imposed'].tolist() if 'Sanctions Imposed' in group.columns else []
    phones = group['Phone number'].tolist() if 'Phone number' in group.columns else []
    emails = group['Email address'].tolist() if 'Email address' in group.columns else []
    imos = group['IMO number'].tolist() if 'IMO number' in group.columns else []
    positions = group['Position'].tolist() if 'Position' in group.columns else []
    
    regimes = group['Regime Name'].dropna().unique()
    regime = regimes[0] if len(regimes) > 0 else ""
    
    # Output Dictionary (OFSI Group ID removed)
    return pd.Series({
        'Unique_ID': group['Unique ID'].iloc[0],
        'Entity_Type': entity_type,
        'Primary_Name': primary_name,
        'Aliases': clean_list(aliases),
        'DOBs': clean_list(dobs),
        'Associated_Countries': clean_list(countries),
        'Passport_Numbers': clean_list(passports),
        'National_IDs': clean_list(nat_ids),
        'IMO_Numbers': clean_list(imos),
        'Phone_Numbers': clean_list(phones),
        'Email_Addresses': clean_list(emails),
        'Positions_Titles': clean_list(positions),
        'Sanctions_Regime': regime,
        'Sanctions_Imposed': clean_list(sanctions)
    })

In [ ]:
temp = df.copy()
temp['Full_Name'] = temp.apply(build_full_name, axis=1)
temp['Clean_Name_Type'] = temp['Name type'].apply(normalise_name_type)
temp['Clean_DOB'] = temp['D.O.B'].apply(clean_dob_for_kyc)
temp['All_Countries_List'] = temp.apply(combine_countries, axis=1)
agg_df = temp.groupby('Unique ID').apply(aggregate_entity).reset_index(drop=True)
agg_df.head(5)

/var/folders/mm/n6ct31451898z276zsj_w5lm0000gn/T/ipykernel_30071/1111755733.py:8: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  agg_df = temp.groupby('Unique ID').apply(aggregate_entity).reset_index(drop=True)

,Unique_ID,Entity_Type,Primary_Name,Aliases,DOBs,Associated_Countries,Passport_Numbers,National_IDs,IMO_Numbers,Phone_Numbers,Email_Addresses,Positions_Titles,Sanctions_Regime,Sanctions_Imposed
0,AFG0001,Entity,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,"Haji Alim Hawala, Haji Hakim Hawala, Haji Khai...",,"Afghanistan, Iran, United Arab Emirates",,,,"'0202-104748, -101823, -103495, -222831, -59763",helmand_exchange_msp@yahoo.com,,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze
1,AFG0002,Entity,ROSHAN MONEY EXCHANGE,"Haji Ahmad Shah Hawala, Maulawi Ahmed Shah Haw...",,"Afghanistan, Pakistan",,,,,,,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze
2,AFG0003,Entity,HAQQANI NETWORK (HQN),,,,,,,,,,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze
3,AFG0004,Entity,RAHAT LTD.,"Haji Muhammad Qasim Sarafi, Musa Kalim Hawala,...",,"Afghanistan, Iran, Pakistan",,,,,,,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze
4,AFG0005,Entity,HAJI BASIR AND ZARJMIL COMPANY HAWALA,"Haji Abdul Basir Exchange Shop, Haji Abdul Bas...",,"Afghanistan, Iran, Pakistan, United Arab Emirates",,,,,,,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze

# Issue Noticed 

1. Issue with phone number which has been fixed in the main script with a clean phone script 
2. Case inconsistent in the name which leads to many duplicate and also the final screening script to not work properly so made them lower case better and faster matching

In [166]:
df[df["Unique ID"] == "AFG0001"][["Name 1","Name 2","Name 3","Name 4","Name 5","Name 6","D.O.B","Regime Name","Designation Type"
,"Sanctions Imposed","National Identifier number","Address Country","Nationality(/ies)","Country of birth"]]

,Name 1,Name 2,Name 3,Name 4,Name 5,Name 6,D.O.B,Regime Name,Designation Type,Sanctions Imposed,National Identifier number,Address Country,Nationality(/ies),Country of birth
0,NaN,NaN,NaN,NaN,NaN,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,Iran,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,Afghanistan,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,Afghanistan,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,Afghanistan,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,HAJI KHAIRULLAH HAJI SATTAR MONEY EXCHANGE,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,Afghanistan,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,NaN,NaN,NaN,NaN,NaN,Sarafi-yi Haji Khairullah Haji Satar Haji Esma...,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,Afghanistan,NaN,NaN
716,NaN,NaN,NaN,NaN,NaN,Sarafi-yi Haji Khairullah Haji Satar Haji Esma...,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,Afghanistan,NaN,NaN
717,NaN,NaN,NaN,NaN,NaN,Sarafi-yi Haji Khairullah Haji Satar Haji Esma...,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,Afghanistan,NaN,NaN
718,NaN,NaN,NaN,NaN,NaN,Sarafi-yi Haji Khairullah Haji Satar Haji Esma...,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,United Arab Emirates,NaN,NaN
719,NaN,NaN,NaN,NaN,NaN,Sarafi-yi Haji Khairullah Haji Satar Haji Esma...,None,The Afghanistan (Sanctions) (EU Exit) Regulati...,Entity,Asset freeze,NaN,Afghanistan,NaN,NaN

In [149]:
len(agg_df["Unique_ID"].unique())

6046

In [150]:
len(df["Unique ID"])

57033

In [165]:
clean = pd.read_csv("sanctions_clean.csv")
clean

,Unique_ID,Entity_Type,Primary_Name,Aliases,DOBs,Gender,Associated_Countries,Passport_Numbers,National_IDs,IMO_Numbers,Phone_Numbers,Email_Addresses,Positions_Titles,Sanctions_Regime,Sanctions_Imposed
0,AFG0001,Entity,haji khairullah haji sattar money exchange,"haji alim hawala, haji hakim hawala, haji khai...",NaN,NaN,"Afghanistan, Iran, United Arab Emirates",NaN,NaN,NaN,0202-104748,helmand_exchange_msp@yahoo.com,NaN,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze
1,AFG0002,Entity,roshan money exchange,"haji ahmad shah hawala, maulawi ahmed shah haw...",NaN,NaN,"Afghanistan, Pakistan",NaN,NaN,NaN,NaN,NaN,NaN,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze
2,AFG0003,Entity,haqqani network (hqn),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze
3,AFG0004,Entity,rahat ltd.,"haji muhammad qasim sarafi, musa kalim hawala,...",NaN,NaN,"Afghanistan, Iran, Pakistan",NaN,NaN,NaN,NaN,NaN,NaN,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze
4,AFG0005,Entity,haji basir and zarjmil company hawala,"haji abdul baseer money changer, haji abdul ba...",NaN,NaN,"Afghanistan, Iran, Pakistan, United Arab Emirates",NaN,NaN,NaN,NaN,NaN,NaN,The Afghanistan (Sanctions) (EU Exit) Regulati...,Asset freeze
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6041,YEM0014,Individual,mohamed nasser al-atifi,nasser al-atifi,1969,NaN,Yemen,NaN,NaN,NaN,NaN,NaN,Houthi Defence Minister,The Yemen (Sanctions) (EU Exit) Regulations 2020,"Asset freeze, Director Disqualification Sancti..."
6042,YEM0015,Individual,muhammad ahmad al-talibi,abu jaafar al-talbi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Yemen (Sanctions) (EU Exit) Regulations 2020,"Asset freeze, Director Disqualification Sancti..."
6043,YEM0016,Individual,muhammad ali al-qadari,NaN,NaN,NaN,Yemen,NaN,NaN,NaN,NaN,NaN,"Director of Houthi Naval College, Houthi Coas...",The Yemen (Sanctions) (EU Exit) Regulations 2020,"Asset freeze, Director Disqualification Sancti..."
6044,YEM0017,Individual,muhammad fadl abd al-nabi,muhammad fadl abdulnabi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Commander of Houthi Naval Forces,The Yemen (Sanctions) (EU Exit) Regulations 2020,"Asset freeze, Director Disqualification Sancti..."
6045,YEM0018,Individual,ali hussein badr al din al-houthi,ali husayn al-huthi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Yemen (Sanctions) (EU Exit) Regulations 2020,"Asset freeze, Director Disqualification Sancti..."

In [167]:
print("Size of the Data after cleaning ",clean.shape)

population_report = clean.notna().mean() * 100
print(population_report.map("{:.1f}% populated".format))


import re
def classify_dob(s):
    s = str(s).strip()
    
    # Catch comma-separated lists generated by the aggregation function
    if ',' in s:
        return 'List of dates (multiple)'
        
    # Existing single-date patterns
    if re.match(r'^\d{2}/\d{2}/\d{4}$', s):        
        return 'Full date (dd/mm/yyyy)'
    if re.match(r'^dd/mm/\d{4}$', s):               
        return 'Year only (dd/mm placeholder)'
    if re.match(r'^dd/\d{2}/\d{4}$', s):               
        return 'Month and Year (mm/yyyy placeholder)'
    if re.match(r'^\d{4}$', s):                     
        return 'Year only (bare yyyy)'
    if re.search(r'(?i)between|circa|approx', s):   
        return 'Approximate (text)'
        
    return 'Other / partial'
dob_series = clean['DOBs'].dropna()
dob_classes = dob_series.apply(classify_dob).value_counts()
print(dob_classes)

print('Sample DOB values by category:')
for cat in dob_classes.index:
    examples = dob_series[dob_series.apply(classify_dob) == cat].unique()[:3]
    print(f'  {cat}: {list(examples)}')


phones = clean['Phone_Numbers'].dropna()
bad = phones[phones.str.startswith("'")]
print(f'Phone numbers with \' {len(bad)}')
print(f'Sample values: {bad.unique().tolist()[:5]}')


exact_dups = clean.duplicated().sum()
uid_only_dups = clean.duplicated(subset=['Unique_ID']).sum()

print(f'Exact duplicate rows         : {exact_dups}')
print(f'Rows with a repeated Unique ID: {uid_only_dups:,} (expected — this is the cross-product design)')

Size of the Data after cleaning  (6046, 15)
Unique_ID               100.0% populated
Entity_Type             100.0% populated
Primary_Name            100.0% populated
Aliases                  46.2% populated
DOBs                     54.1% populated
Gender                   48.1% populated
Associated_Countries     78.4% populated
Passport_Numbers          9.4% populated
National_IDs              6.2% populated
IMO_Numbers              10.4% populated
Phone_Numbers            10.1% populated
Email_Addresses           8.4% populated
Positions_Titles         43.7% populated
Sanctions_Regime        100.0% populated
Sanctions_Imposed       100.0% populated
dtype: object
DOBs
Full date (dd/mm/yyyy)      2567
Year only (bare yyyy)        448
List of dates (multiple)     239
Other / partial               18
Name: count, dtype: int64
Sample DOB values by category:
  Full date (dd/mm/yyyy): ['29/03/1965', '06/03/1973', '03/08/1986']
  Year only (bare yyyy): ['1961', '1965', '1969']
  List of dates (multiple): ['1945, 1946, 1947, 1948, 1949, 1950, 1955, 1956, 1957, 1958', '1963, 30/01/1972', '1953, 1960, 1966']
  Other / partial: ['09/1958', '11/1973', '07/1976']
Phone numbers with ' 0
Sample values: []
Exact duplicate rows         : 0
Rows with a repeated Unique ID: 0 (expected — this is the cross-product design)